// Code generated by protoc-gen-go.
// source: adviewresp.proto
// DO NOT EDIT!

/*
Package adviewresp is a generated protocol buffer package.

It is generated from these files:
	adviewresp.proto

It has these top-level messages:
	AdResponse
*/
package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type AdResponse struct {
	Id               *string          `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Ads              []*AdResponse_Ad `protobuf:"bytes,2,rep,name=ads" json:"ads,omitempty"`
	Reqid            *string          `protobuf:"bytes,3,opt,name=reqid" json:"reqid,omitempty"`
	Cur              *string          `protobuf:"bytes,4,opt,name=cur" json:"cur,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AdResponse) Reset()                    { *m = AdResponse{} }
func (m *AdResponse) String() string            { return proto.CompactTextString(m) }
func (*AdResponse) ProtoMessage()               {}
func (*AdResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *AdResponse) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AdResponse) GetAds() []*AdResponse_Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *AdResponse) GetReqid() string {
	if m != nil && m.Reqid != nil {
		return *m.Reqid
	}
	return ""
}

func (m *AdResponse) GetCur() string {
	if m != nil && m.Cur != nil {
		return *m.Cur
	}
	return ""
}

type AdResponse_Ad struct {
	Impid            *string               `protobuf:"bytes,1,req,name=impid" json:"impid,omitempty"`
	Price            *int32                `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	Pmd              *string               `protobuf:"bytes,3,opt,name=pmd" json:"pmd,omitempty"`
	Adid             *string               `protobuf:"bytes,4,opt,name=adid" json:"adid,omitempty"`
	Admt             *int32                `protobuf:"varint,5,opt,name=admt" json:"admt,omitempty"`
	Adm              *string               `protobuf:"bytes,6,opt,name=adm" json:"adm,omitempty"`
	Native           *AdResponse_Ad_Native `protobuf:"bytes,7,opt,name=native" json:"native,omitempty"`
	Adi              *string               `protobuf:"bytes,8,opt,name=adi" json:"adi,omitempty"`
	Adt              *string               `protobuf:"bytes,9,opt,name=adt" json:"adt,omitempty"`
	Ads              *string               `protobuf:"bytes,10,opt,name=ads" json:"ads,omitempty"`
	Adw              *int32                `protobuf:"varint,11,opt,name=adw" json:"adw,omitempty"`
	Adh              *int32                `protobuf:"varint,12,opt,name=adh" json:"adh,omitempty"`
	Adct             *int32                `protobuf:"varint,13,opt,name=adct" json:"adct,omitempty"`
	Adtm             *int32                `protobuf:"varint,14,opt,name=adtm" json:"adtm,omitempty"`
	Ade              *int32                `protobuf:"varint,15,opt,name=ade" json:"ade,omitempty"`
	Adurl            *string               `protobuf:"bytes,16,opt,name=adurl" json:"adurl,omitempty"`
	Adomain          *string               `protobuf:"bytes,17,opt,name=adomain" json:"adomain,omitempty"`
	Nurl             []string              `protobuf:"bytes,18,rep,name=nurl" json:"nurl,omitempty"`
	Curl             []string              `protobuf:"bytes,19,rep,name=curl" json:"curl,omitempty"`
	Cid              *string               `protobuf:"bytes,20,opt,name=cid" json:"cid,omitempty"`
	Crid             *string               `protobuf:"bytes,21,opt,name=crid" json:"crid,omitempty"`
	Attr             []string              `protobuf:"bytes,22,rep,name=attr" json:"attr,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *AdResponse_Ad) Reset()                    { *m = AdResponse_Ad{} }
func (m *AdResponse_Ad) String() string            { return proto.CompactTextString(m) }
func (*AdResponse_Ad) ProtoMessage()               {}
func (*AdResponse_Ad) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

func (m *AdResponse_Ad) GetImpid() string {
	if m != nil && m.Impid != nil {
		return *m.Impid
	}
	return ""
}

func (m *AdResponse_Ad) GetPrice() int32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *AdResponse_Ad) GetPmd() string {
	if m != nil && m.Pmd != nil {
		return *m.Pmd
	}
	return ""
}

func (m *AdResponse_Ad) GetAdid() string {
	if m != nil && m.Adid != nil {
		return *m.Adid
	}
	return ""
}

func (m *AdResponse_Ad) GetAdmt() int32 {
	if m != nil && m.Admt != nil {
		return *m.Admt
	}
	return 0
}

func (m *AdResponse_Ad) GetAdm() string {
	if m != nil && m.Adm != nil {
		return *m.Adm
	}
	return ""
}

func (m *AdResponse_Ad) GetNative() *AdResponse_Ad_Native {
	if m != nil {
		return m.Native
	}
	return nil
}

func (m *AdResponse_Ad) GetAdi() string {
	if m != nil && m.Adi != nil {
		return *m.Adi
	}
	return ""
}

func (m *AdResponse_Ad) GetAdt() string {
	if m != nil && m.Adt != nil {
		return *m.Adt
	}
	return ""
}

func (m *AdResponse_Ad) GetAds() string {
	if m != nil && m.Ads != nil {
		return *m.Ads
	}
	return ""
}

func (m *AdResponse_Ad) GetAdw() int32 {
	if m != nil && m.Adw != nil {
		return *m.Adw
	}
	return 0
}

func (m *AdResponse_Ad) GetAdh() int32 {
	if m != nil && m.Adh != nil {
		return *m.Adh
	}
	return 0
}

func (m *AdResponse_Ad) GetAdct() int32 {
	if m != nil && m.Adct != nil {
		return *m.Adct
	}
	return 0
}

func (m *AdResponse_Ad) GetAdtm() int32 {
	if m != nil && m.Adtm != nil {
		return *m.Adtm
	}
	return 0
}

func (m *AdResponse_Ad) GetAde() int32 {
	if m != nil && m.Ade != nil {
		return *m.Ade
	}
	return 0
}

func (m *AdResponse_Ad) GetAdurl() string {
	if m != nil && m.Adurl != nil {
		return *m.Adurl
	}
	return ""
}

func (m *AdResponse_Ad) GetAdomain() string {
	if m != nil && m.Adomain != nil {
		return *m.Adomain
	}
	return ""
}

func (m *AdResponse_Ad) GetNurl() []string {
	if m != nil {
		return m.Nurl
	}
	return nil
}

func (m *AdResponse_Ad) GetCurl() []string {
	if m != nil {
		return m.Curl
	}
	return nil
}

func (m *AdResponse_Ad) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

func (m *AdResponse_Ad) GetCrid() string {
	if m != nil && m.Crid != nil {
		return *m.Crid
	}
	return ""
}

func (m *AdResponse_Ad) GetAttr() []string {
	if m != nil {
		return m.Attr
	}
	return nil
}

type AdResponse_Ad_Native struct {
	Request          *string `protobuf:"bytes,1,req,name=request" json:"request,omitempty"`
	Ver              *string `protobuf:"bytes,2,req,name=ver" json:"ver,omitempty"`
	Api              []int32 `protobuf:"varint,3,rep,name=api" json:"api,omitempty"`
	Battr            []int32 `protobuf:"varint,4,rep,name=battr" json:"battr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AdResponse_Ad_Native) Reset()                    { *m = AdResponse_Ad_Native{} }
func (m *AdResponse_Ad_Native) String() string            { return proto.CompactTextString(m) }
func (*AdResponse_Ad_Native) ProtoMessage()               {}
func (*AdResponse_Ad_Native) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0, 0} }

func (m *AdResponse_Ad_Native) GetRequest() string {
	if m != nil && m.Request != nil {
		return *m.Request
	}
	return ""
}

func (m *AdResponse_Ad_Native) GetVer() string {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return ""
}

func (m *AdResponse_Ad_Native) GetApi() []int32 {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *AdResponse_Ad_Native) GetBattr() []int32 {
	if m != nil {
		return m.Battr
	}
	return nil
}

func init() {
	proto.RegisterType((*AdResponse)(nil), "AdResponse")
	proto.RegisterType((*AdResponse_Ad)(nil), "AdResponse.Ad")
	proto.RegisterType((*AdResponse_Ad_Native)(nil), "AdResponse.Ad.Native")
}

var fileDescriptor2 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0x38, 0x4d, 0xe9, 0xa4, 0x7f, 0x04, 0x8a, 0x46, 0x65, 0x13, 0x21, 0x21, 0x65,
	0x95, 0x45, 0x6f, 0x00, 0x07, 0x60, 0xc1, 0x0d, 0x4c, 0x6c, 0x09, 0x4b, 0x24, 0x31, 0x8e, 0x93,
	0xde, 0x83, 0x43, 0x72, 0x0e, 0xc6, 0x4e, 0x52, 0x8b, 0x5d, 0xbe, 0xcc, 0x9b, 0xe7, 0x79, 0x0f,
	0x0e, 0x5c, 0x0c, 0x4a, 0x5e, 0x8c, 0xec, 0x74, 0xa9, 0x4d, 0x6b, 0xdb, 0xa7, 0x5f, 0x06, 0xf0,
	0x22, 0xde, 0xe9, 0x47, 0xdb, 0x74, 0x32, 0x03, 0x88, 0x94, 0xc0, 0x45, 0x1e, 0x15, 0xeb, 0xec,
	0x11, 0x18, 0x17, 0x1d, 0x46, 0x39, 0x2b, 0xd2, 0xf3, 0xae, 0x0c, 0x2a, 0xfa, 0xcc, 0xb6, 0xb0,
	0x34, 0xf2, 0x9b, 0xb4, 0x2c, 0x5f, 0x90, 0x36, 0x05, 0x56, 0xf5, 0x06, 0x63, 0x07, 0xa7, 0x1f,
	0x06, 0xd1, 0x28, 0x51, 0xb5, 0xbe, 0xda, 0x11, 0x6a, 0xa3, 0x2a, 0x49, 0x86, 0x8b, 0x62, 0xe9,
	0x36, 0x74, 0x3d, 0xaf, 0x6f, 0x20, 0xe6, 0x82, 0x94, 0x71, 0xa0, 0xda, 0xe2, 0x72, 0x16, 0x12,
	0x61, 0xe2, 0x47, 0xcf, 0x90, 0x34, 0xdc, 0xaa, 0x41, 0xe2, 0x8a, 0x38, 0x3d, 0x1f, 0xff, 0x9f,
	0x55, 0xbe, 0xf9, 0xe1, 0xb8, 0xa3, 0xf0, 0x66, 0xbe, 0x8d, 0x0b, 0x8b, 0xeb, 0x00, 0x1d, 0x42,
	0x80, 0x0b, 0xa6, 0xe1, 0x9d, 0x4f, 0xdc, 0x78, 0xf0, 0x27, 0x54, 0x16, 0xb7, 0x81, 0x6c, 0x8d,
	0xbb, 0x20, 0x94, 0xb8, 0xf7, 0x40, 0xa9, 0xb8, 0xe8, 0xcd, 0x17, 0x1e, 0xbc, 0xe3, 0x1e, 0x56,
	0x5c, 0xb4, 0x35, 0x57, 0x0d, 0xde, 0xce, 0x59, 0x1a, 0x37, 0xce, 0xa8, 0x45, 0x4f, 0x95, 0xa3,
	0x3b, 0x4f, 0xae, 0x34, 0x0a, 0x7d, 0x3f, 0x0b, 0x2b, 0x43, 0x74, 0xbc, 0x56, 0x60, 0xad, 0xc1,
	0x07, 0x27, 0x3c, 0xbd, 0x42, 0x32, 0x05, 0x23, 0x7f, 0xaa, 0xbd, 0x97, 0x9d, 0x9d, 0x5a, 0x25,
	0x8f, 0x41, 0x1a, 0xea, 0x74, 0x02, 0xae, 0x15, 0x75, 0xca, 0xc6, 0xcb, 0x3e, 0xbc, 0x47, 0xec,
	0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x7a, 0x00, 0x7d, 0xfb, 0x01, 0x00, 0x00,
}
