// Code generated by protoc-gen-go.
// source: baiduwifi.proto
// DO NOT EDIT!

/*
Package baiduwifi is a generated protocol buffer package.

It is generated from these files:
	baiduwifi.proto

It has these top-level messages:
	Mobile
*/
package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// 设备类型定义
type Mobile_MobileDeviceType int32

const (
	Mobile_UNKNOWN_DEVICE Mobile_MobileDeviceType = 0
	Mobile_HIGHEND_PHONE  Mobile_MobileDeviceType = 1
	Mobile_TABLET         Mobile_MobileDeviceType = 2
)

var Mobile_MobileDeviceType_name = map[int32]string{
	0: "UNKNOWN_DEVICE",
	1: "HIGHEND_PHONE",
	2: "TABLET",
}
var Mobile_MobileDeviceType_value = map[string]int32{
	"UNKNOWN_DEVICE": 0,
	"HIGHEND_PHONE":  1,
	"TABLET":         2,
}

func (x Mobile_MobileDeviceType) Enum() *Mobile_MobileDeviceType {
	p := new(Mobile_MobileDeviceType)
	*p = x
	return p
}
func (x Mobile_MobileDeviceType) String() string {
	return proto.EnumName(Mobile_MobileDeviceType_name, int32(x))
}
func (x *Mobile_MobileDeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mobile_MobileDeviceType_value, data, "Mobile_MobileDeviceType")
	if err != nil {
		return err
	}
	*x = Mobile_MobileDeviceType(value)
	return nil
}
func (Mobile_MobileDeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// 移动平台名，例如android，iphone等等
type Mobile_OS int32

const (
	Mobile_UNKNOWN_OS    Mobile_OS = 0
	Mobile_IOS           Mobile_OS = 1
	Mobile_ANDROID       Mobile_OS = 2
	Mobile_WINDOWS_PHONE Mobile_OS = 3
)

var Mobile_OS_name = map[int32]string{
	0: "UNKNOWN_OS",
	1: "IOS",
	2: "ANDROID",
	3: "WINDOWS_PHONE",
}
var Mobile_OS_value = map[string]int32{
	"UNKNOWN_OS":    0,
	"IOS":           1,
	"ANDROID":       2,
	"WINDOWS_PHONE": 3,
}

func (x Mobile_OS) Enum() *Mobile_OS {
	p := new(Mobile_OS)
	*p = x
	return p
}
func (x Mobile_OS) String() string {
	return proto.EnumName(Mobile_OS_name, int32(x))
}
func (x *Mobile_OS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mobile_OS_value, data, "Mobile_OS")
	if err != nil {
		return err
	}
	*x = Mobile_OS(value)
	return nil
}
func (Mobile_OS) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

// 无线网络类型
type Mobile_WirelessNetworkType int32

const (
	Mobile_UNKNOWN_NETWORK Mobile_WirelessNetworkType = 0
	Mobile_WIFI            Mobile_WirelessNetworkType = 1
	Mobile_MOBILE_2G       Mobile_WirelessNetworkType = 2
	Mobile_MOBILE_3G       Mobile_WirelessNetworkType = 3
	Mobile_MOBILE_4G       Mobile_WirelessNetworkType = 4
)

var Mobile_WirelessNetworkType_name = map[int32]string{
	0: "UNKNOWN_NETWORK",
	1: "WIFI",
	2: "MOBILE_2G",
	3: "MOBILE_3G",
	4: "MOBILE_4G",
}
var Mobile_WirelessNetworkType_value = map[string]int32{
	"UNKNOWN_NETWORK": 0,
	"WIFI":            1,
	"MOBILE_2G":       2,
	"MOBILE_3G":       3,
	"MOBILE_4G":       4,
}

func (x Mobile_WirelessNetworkType) Enum() *Mobile_WirelessNetworkType {
	p := new(Mobile_WirelessNetworkType)
	*p = x
	return p
}
func (x Mobile_WirelessNetworkType) String() string {
	return proto.EnumName(Mobile_WirelessNetworkType_name, int32(x))
}
func (x *Mobile_WirelessNetworkType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mobile_WirelessNetworkType_value, data, "Mobile_WirelessNetworkType")
	if err != nil {
		return err
	}
	*x = Mobile_WirelessNetworkType(value)
	return nil
}
func (Mobile_WirelessNetworkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2}
}

// 移动设备ID的类型
type Mobile_MobileID_IDType int32

const (
	// 未知
	Mobile_MobileID_UNKNOWN Mobile_MobileID_IDType = 0
	// IMEI
	Mobile_MobileID_IMEI Mobile_MobileID_IDType = 1
	// MAC地址
	Mobile_MobileID_MAC Mobile_MobileID_IDType = 2
)

var Mobile_MobileID_IDType_name = map[int32]string{
	0: "UNKNOWN",
	1: "IMEI",
	2: "MAC",
}
var Mobile_MobileID_IDType_value = map[string]int32{
	"UNKNOWN": 0,
	"IMEI":    1,
	"MAC":     2,
}

func (x Mobile_MobileID_IDType) Enum() *Mobile_MobileID_IDType {
	p := new(Mobile_MobileID_IDType)
	*p = x
	return p
}
func (x Mobile_MobileID_IDType) String() string {
	return proto.EnumName(Mobile_MobileID_IDType_name, int32(x))
}
func (x *Mobile_MobileID_IDType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mobile_MobileID_IDType_value, data, "Mobile_MobileID_IDType")
	if err != nil {
		return err
	}
	*x = Mobile_MobileID_IDType(value)
	return nil
}
func (Mobile_MobileID_IDType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0, 0} }

type Mobile_ForAdvertisingID_IDType int32

const (
	Mobile_ForAdvertisingID_UNKNOWN    Mobile_ForAdvertisingID_IDType = 0
	Mobile_ForAdvertisingID_ANDROID_ID Mobile_ForAdvertisingID_IDType = 4
	Mobile_ForAdvertisingID_IDFA       Mobile_ForAdvertisingID_IDType = 5
)

var Mobile_ForAdvertisingID_IDType_name = map[int32]string{
	0: "UNKNOWN",
	4: "ANDROID_ID",
	5: "IDFA",
}
var Mobile_ForAdvertisingID_IDType_value = map[string]int32{
	"UNKNOWN":    0,
	"ANDROID_ID": 4,
	"IDFA":       5,
}

func (x Mobile_ForAdvertisingID_IDType) Enum() *Mobile_ForAdvertisingID_IDType {
	p := new(Mobile_ForAdvertisingID_IDType)
	*p = x
	return p
}
func (x Mobile_ForAdvertisingID_IDType) String() string {
	return proto.EnumName(Mobile_ForAdvertisingID_IDType_name, int32(x))
}
func (x *Mobile_ForAdvertisingID_IDType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mobile_ForAdvertisingID_IDType_value, data, "Mobile_ForAdvertisingID_IDType")
	if err != nil {
		return err
	}
	*x = Mobile_ForAdvertisingID_IDType(value)
	return nil
}
func (Mobile_ForAdvertisingID_IDType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2, 0}
}

// App允许的交互类型定义
// 电话、下载
type Mobile_MobileApp_AppInteractionType int32

const (
	Mobile_MobileApp_TELEPHONE Mobile_MobileApp_AppInteractionType = 0
	Mobile_MobileApp_DOWNLOAD  Mobile_MobileApp_AppInteractionType = 1
)

var Mobile_MobileApp_AppInteractionType_name = map[int32]string{
	0: "TELEPHONE",
	1: "DOWNLOAD",
}
var Mobile_MobileApp_AppInteractionType_value = map[string]int32{
	"TELEPHONE": 0,
	"DOWNLOAD":  1,
}

func (x Mobile_MobileApp_AppInteractionType) Enum() *Mobile_MobileApp_AppInteractionType {
	p := new(Mobile_MobileApp_AppInteractionType)
	*p = x
	return p
}
func (x Mobile_MobileApp_AppInteractionType) String() string {
	return proto.EnumName(Mobile_MobileApp_AppInteractionType_name, int32(x))
}
func (x *Mobile_MobileApp_AppInteractionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Mobile_MobileApp_AppInteractionType_value, data, "Mobile_MobileApp_AppInteractionType")
	if err != nil {
		return err
	}
	*x = Mobile_MobileApp_AppInteractionType(value)
	return nil
}
func (Mobile_MobileApp_AppInteractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 3, 0}
}

// **** 移动设备信息 ****
type Mobile struct {
	Id []*Mobile_MobileID `protobuf:"bytes,13,rep,name=id" json:"id,omitempty"`
	// 设备类型
	DeviceType *Mobile_MobileDeviceType `protobuf:"varint,2,opt,name=device_type,enum=Mobile_MobileDeviceType" json:"device_type,omitempty"`
	Platform   *Mobile_OS               `protobuf:"varint,3,opt,name=platform,enum=Mobile_OS,def=0" json:"platform,omitempty"`
	OsVersion  *Mobile_DeviceOsVersion  `protobuf:"bytes,4,opt,name=os_version" json:"os_version,omitempty"`
	// 设备品牌
	Brand *string `protobuf:"bytes,5,opt,name=brand" json:"brand,omitempty"`
	// 设备机型
	Model *string `protobuf:"bytes,6,opt,name=model" json:"model,omitempty"`
	// 设备屏宽
	ScreenWidth *int32 `protobuf:"varint,7,opt,name=screen_width" json:"screen_width,omitempty"`
	// 设备屏高
	ScreenHeight *int32 `protobuf:"varint,8,opt,name=screen_height" json:"screen_height,omitempty"`
	// 运营商编号（MCC+MNC编号）
	// 例如中国移动 46000
	// 前三位是Mobile Country Code
	// 后两位是Mobile Network Code
	CarrierId           *int64                      `protobuf:"varint,9,opt,name=carrier_id" json:"carrier_id,omitempty"`
	WirelessNetworkType *Mobile_WirelessNetworkType `protobuf:"varint,10,opt,name=wireless_network_type,enum=Mobile_WirelessNetworkType" json:"wireless_network_type,omitempty"`
	ForAdvertisingId    []*Mobile_ForAdvertisingID  `protobuf:"bytes,14,rep,name=for_advertising_id" json:"for_advertising_id,omitempty"`
	// 移动应用信息，当流量来自App时该字段非空
	MobileApp        *Mobile_MobileApp `protobuf:"bytes,12,opt,name=mobile_app" json:"mobile_app,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Mobile) Reset()                    { *m = Mobile{} }
func (m *Mobile) String() string            { return proto.CompactTextString(m) }
func (*Mobile) ProtoMessage()               {}
func (*Mobile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Mobile_Platform Mobile_OS = Mobile_UNKNOWN_OS

func (m *Mobile) GetId() []*Mobile_MobileID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Mobile) GetDeviceType() Mobile_MobileDeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Mobile_UNKNOWN_DEVICE
}

func (m *Mobile) GetPlatform() Mobile_OS {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Default_Mobile_Platform
}

func (m *Mobile) GetOsVersion() *Mobile_DeviceOsVersion {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Mobile) GetBrand() string {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return ""
}

func (m *Mobile) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Mobile) GetScreenWidth() int32 {
	if m != nil && m.ScreenWidth != nil {
		return *m.ScreenWidth
	}
	return 0
}

func (m *Mobile) GetScreenHeight() int32 {
	if m != nil && m.ScreenHeight != nil {
		return *m.ScreenHeight
	}
	return 0
}

func (m *Mobile) GetCarrierId() int64 {
	if m != nil && m.CarrierId != nil {
		return *m.CarrierId
	}
	return 0
}

func (m *Mobile) GetWirelessNetworkType() Mobile_WirelessNetworkType {
	if m != nil && m.WirelessNetworkType != nil {
		return *m.WirelessNetworkType
	}
	return Mobile_UNKNOWN_NETWORK
}

func (m *Mobile) GetForAdvertisingId() []*Mobile_ForAdvertisingID {
	if m != nil {
		return m.ForAdvertisingId
	}
	return nil
}

func (m *Mobile) GetMobileApp() *Mobile_MobileApp {
	if m != nil {
		return m.MobileApp
	}
	return nil
}

// 新版移动设备序列号标识字段。允许同时存储多个序列号
type Mobile_MobileID struct {
	Type             *Mobile_MobileID_IDType `protobuf:"varint,1,opt,name=type,enum=Mobile_MobileID_IDType" json:"type,omitempty"`
	Id               *string                 `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Mobile_MobileID) Reset()                    { *m = Mobile_MobileID{} }
func (m *Mobile_MobileID) String() string            { return proto.CompactTextString(m) }
func (*Mobile_MobileID) ProtoMessage()               {}
func (*Mobile_MobileID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Mobile_MobileID) GetType() Mobile_MobileID_IDType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Mobile_MobileID_UNKNOWN
}

func (m *Mobile_MobileID) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

// 移动操作系统版本号
// 例如 Android 2.1, major, micro分别是2,1
// 例如 Iphone 4.2.1，major, minor, micro分别是4,2,1
type Mobile_DeviceOsVersion struct {
	OsVersionMajor   *int32 `protobuf:"varint,1,opt,name=os_version_major" json:"os_version_major,omitempty"`
	OsVersionMinor   *int32 `protobuf:"varint,2,opt,name=os_version_minor" json:"os_version_minor,omitempty"`
	OsVersionMicro   *int32 `protobuf:"varint,3,opt,name=os_version_micro" json:"os_version_micro,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Mobile_DeviceOsVersion) Reset()                    { *m = Mobile_DeviceOsVersion{} }
func (m *Mobile_DeviceOsVersion) String() string            { return proto.CompactTextString(m) }
func (*Mobile_DeviceOsVersion) ProtoMessage()               {}
func (*Mobile_DeviceOsVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Mobile_DeviceOsVersion) GetOsVersionMajor() int32 {
	if m != nil && m.OsVersionMajor != nil {
		return *m.OsVersionMajor
	}
	return 0
}

func (m *Mobile_DeviceOsVersion) GetOsVersionMinor() int32 {
	if m != nil && m.OsVersionMinor != nil {
		return *m.OsVersionMinor
	}
	return 0
}

func (m *Mobile_DeviceOsVersion) GetOsVersionMicro() int32 {
	if m != nil && m.OsVersionMicro != nil {
		return *m.OsVersionMicro
	}
	return 0
}

// 新版移动设备用户识别号字段，允许多种类型同时存在
// 推荐使用本字段获取用户ID，原字段会逐步废弃。
type Mobile_ForAdvertisingID struct {
	Type             *Mobile_ForAdvertisingID_IDType `protobuf:"varint,1,opt,name=type,enum=Mobile_ForAdvertisingID_IDType" json:"type,omitempty"`
	Id               *string                         `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *Mobile_ForAdvertisingID) Reset()                    { *m = Mobile_ForAdvertisingID{} }
func (m *Mobile_ForAdvertisingID) String() string            { return proto.CompactTextString(m) }
func (*Mobile_ForAdvertisingID) ProtoMessage()               {}
func (*Mobile_ForAdvertisingID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Mobile_ForAdvertisingID) GetType() Mobile_ForAdvertisingID_IDType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Mobile_ForAdvertisingID_UNKNOWN
}

func (m *Mobile_ForAdvertisingID) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

// **** 移动应用信息 ****
type Mobile_MobileApp struct {
	// 百度移动联盟为该App分配的app id
	AppId *string `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	// 如果来自苹果商店，则直接是app-store id
	// 如果来自Android设备，则是package的全名
	AppBundleId *string `protobuf:"bytes,2,opt,name=app_bundle_id" json:"app_bundle_id,omitempty"`
	// App应用分类
	AppCategory *int32 `protobuf:"varint,3,opt,name=app_category" json:"app_category,omitempty"`
	// App开发者ID
	AppPublisherId *int32 `protobuf:"varint,4,opt,name=app_publisher_id" json:"app_publisher_id,omitempty"`
	// App允许的交互类型
	AppInteractionType []Mobile_MobileApp_AppInteractionType `protobuf:"varint,5,rep,name=app_interaction_type,enum=Mobile_MobileApp_AppInteractionType" json:"app_interaction_type,omitempty"`
	// App应用标题
	AppTitle *string `protobuf:"bytes,6,opt,name=app_title" json:"app_title,omitempty"`
	// App应用关键词
	AppKeywords *string `protobuf:"bytes,7,opt,name=app_keywords" json:"app_keywords,omitempty"`
	// App是否收费
	AppPaid          *bool  `protobuf:"varint,8,opt,name=app_paid" json:"app_paid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Mobile_MobileApp) Reset()                    { *m = Mobile_MobileApp{} }
func (m *Mobile_MobileApp) String() string            { return proto.CompactTextString(m) }
func (*Mobile_MobileApp) ProtoMessage()               {}
func (*Mobile_MobileApp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Mobile_MobileApp) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *Mobile_MobileApp) GetAppBundleId() string {
	if m != nil && m.AppBundleId != nil {
		return *m.AppBundleId
	}
	return ""
}

func (m *Mobile_MobileApp) GetAppCategory() int32 {
	if m != nil && m.AppCategory != nil {
		return *m.AppCategory
	}
	return 0
}

func (m *Mobile_MobileApp) GetAppPublisherId() int32 {
	if m != nil && m.AppPublisherId != nil {
		return *m.AppPublisherId
	}
	return 0
}

func (m *Mobile_MobileApp) GetAppInteractionType() []Mobile_MobileApp_AppInteractionType {
	if m != nil {
		return m.AppInteractionType
	}
	return nil
}

func (m *Mobile_MobileApp) GetAppTitle() string {
	if m != nil && m.AppTitle != nil {
		return *m.AppTitle
	}
	return ""
}

func (m *Mobile_MobileApp) GetAppKeywords() string {
	if m != nil && m.AppKeywords != nil {
		return *m.AppKeywords
	}
	return ""
}

func (m *Mobile_MobileApp) GetAppPaid() bool {
	if m != nil && m.AppPaid != nil {
		return *m.AppPaid
	}
	return false
}

func init() {
	proto.RegisterType((*Mobile)(nil), "Mobile")
	proto.RegisterType((*Mobile_MobileID)(nil), "Mobile.MobileID")
	proto.RegisterType((*Mobile_DeviceOsVersion)(nil), "Mobile.DeviceOsVersion")
	proto.RegisterType((*Mobile_ForAdvertisingID)(nil), "Mobile.ForAdvertisingID")
	proto.RegisterType((*Mobile_MobileApp)(nil), "Mobile.MobileApp")
	proto.RegisterEnum("Mobile_MobileDeviceType", Mobile_MobileDeviceType_name, Mobile_MobileDeviceType_value)
	proto.RegisterEnum("Mobile_OS", Mobile_OS_name, Mobile_OS_value)
	proto.RegisterEnum("Mobile_WirelessNetworkType", Mobile_WirelessNetworkType_name, Mobile_WirelessNetworkType_value)
	proto.RegisterEnum("Mobile_MobileID_IDType", Mobile_MobileID_IDType_name, Mobile_MobileID_IDType_value)
	proto.RegisterEnum("Mobile_ForAdvertisingID_IDType", Mobile_ForAdvertisingID_IDType_name, Mobile_ForAdvertisingID_IDType_value)
	proto.RegisterEnum("Mobile_MobileApp_AppInteractionType", Mobile_MobileApp_AppInteractionType_name, Mobile_MobileApp_AppInteractionType_value)
}

var fileDescriptor0 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0x5f, 0x4f, 0xe2, 0x4a,
	0x14, 0xbf, 0x94, 0x3f, 0xd2, 0x83, 0xe0, 0x38, 0x6a, 0x6c, 0xb8, 0x37, 0xb9, 0x86, 0x5c, 0x13,
	0x92, 0x1b, 0xd9, 0x2c, 0xeb, 0x93, 0xc9, 0x3e, 0xa0, 0xad, 0xd8, 0x08, 0xed, 0x46, 0x59, 0x79,
	0x6c, 0x0a, 0x1d, 0x61, 0x56, 0x68, 0x9b, 0x69, 0x95, 0xf8, 0xb2, 0x9f, 0x62, 0x3f, 0xe7, 0x7e,
	0x86, 0x3d, 0x33, 0x05, 0x59, 0x95, 0x7d, 0x20, 0x74, 0xce, 0xf9, 0xf5, 0x74, 0x7e, 0x7f, 0x0e,
	0xec, 0x8c, 0x7c, 0x1e, 0x3c, 0x2e, 0xf8, 0x3d, 0x6f, 0xc5, 0x22, 0x4a, 0xa3, 0xc6, 0x4f, 0x1d,
	0x4a, 0xfd, 0x68, 0xc4, 0x67, 0x8c, 0xfe, 0x03, 0x1a, 0x0f, 0x8c, 0xea, 0x51, 0xbe, 0x59, 0x69,
	0x93, 0x56, 0x56, 0x5c, 0xfe, 0xd9, 0x26, 0x3d, 0x81, 0x4a, 0xc0, 0x9e, 0xf8, 0x98, 0x79, 0xe9,
	0x73, 0xcc, 0x0c, 0xed, 0x28, 0xd7, 0xac, 0xb5, 0x8d, 0xd7, 0x30, 0x53, 0x01, 0x06, 0xd8, 0xa7,
	0x4d, 0x28, 0xc7, 0x33, 0x3f, 0xbd, 0x8f, 0xc4, 0xdc, 0xc8, 0x2b, 0x2c, 0xac, 0xb0, 0xee, 0xed,
	0x19, 0x7c, 0x75, 0xae, 0x1d, 0x77, 0xe8, 0x78, 0xee, 0x2d, 0xfd, 0x1f, 0x20, 0x4a, 0xbc, 0x27,
	0x26, 0x12, 0x1e, 0x85, 0x46, 0x01, 0xb1, 0x95, 0xf6, 0xe1, 0x0a, 0x9b, 0x4d, 0x74, 0x93, 0xbb,
	0xac, 0x4d, 0xab, 0x50, 0x1c, 0x09, 0x3f, 0x0c, 0x8c, 0x22, 0xe2, 0x74, 0x79, 0x9c, 0x47, 0x01,
	0x9b, 0x19, 0x25, 0x75, 0xdc, 0x87, 0xed, 0x64, 0x2c, 0x18, 0x0b, 0xbd, 0x05, 0x0f, 0xd2, 0xa9,
	0xb1, 0x85, 0xd5, 0x22, 0x3d, 0x80, 0xea, 0xb2, 0x3a, 0x65, 0x7c, 0x32, 0x4d, 0x8d, 0xb2, 0x2a,
	0x53, 0x80, 0xb1, 0x2f, 0x04, 0x67, 0xc2, 0x43, 0xda, 0x3a, 0xd6, 0xf2, 0xf4, 0x0c, 0x0e, 0x16,
	0x5c, 0xb0, 0x19, 0x4b, 0x12, 0x2f, 0x64, 0xe9, 0x22, 0x12, 0x0f, 0x19, 0x5d, 0x50, 0x14, 0xfe,
	0x5e, 0x5d, 0x6b, 0xb8, 0x04, 0x39, 0x19, 0x46, 0x31, 0x3e, 0x05, 0x8a, 0x6c, 0x3d, 0x3f, 0x40,
	0x2a, 0x29, 0x4f, 0x78, 0x38, 0x91, 0x73, 0x6b, 0x4a, 0xce, 0x17, 0x9d, 0x2e, 0x23, 0xd1, 0x59,
	0x03, 0x50, 0xd6, 0x63, 0x80, 0xb9, 0x6a, 0x79, 0x7e, 0x1c, 0x1b, 0xdb, 0x8a, 0xfd, 0xee, 0x6b,
	0x55, 0x3b, 0x71, 0x5c, 0x9f, 0x40, 0xf9, 0xc5, 0x89, 0x63, 0x28, 0xa8, 0x3b, 0xe5, 0xd4, 0x9d,
	0x0e, 0xdf, 0x3a, 0xd5, 0xb2, 0x4d, 0x75, 0x1f, 0x50, 0x76, 0x4a, 0x9f, 0xf4, 0x46, 0x13, 0x4a,
	0xcb, 0x6a, 0x05, 0xb6, 0x96, 0xda, 0x93, 0xbf, 0x68, 0x19, 0x0a, 0x76, 0xdf, 0xb2, 0x49, 0x8e,
	0x6e, 0x41, 0xbe, 0xdf, 0xb9, 0x20, 0x5a, 0xdd, 0x83, 0x9d, 0xb7, 0x9a, 0x1b, 0x40, 0xd6, 0x06,
	0x79, 0x73, 0xff, 0x5b, 0x24, 0xd4, 0xb7, 0x8b, 0x6f, 0x3b, 0x3c, 0xc4, 0x8e, 0xb6, 0xb1, 0x33,
	0x16, 0x91, 0x8a, 0x41, 0xb1, 0xfe, 0x1d, 0xc8, 0x3b, 0x11, 0x4e, 0x5e, 0x31, 0xfa, 0xf7, 0x4f,
	0x62, 0x6d, 0x62, 0xf6, 0x61, 0x33, 0xb3, 0x1a, 0x40, 0xc7, 0x31, 0x6f, 0x5c, 0xdb, 0xf4, 0x6c,
	0x93, 0x14, 0x14, 0x53, 0xf3, 0xb2, 0x43, 0x8a, 0xf5, 0x1f, 0x1a, 0xe8, 0x2f, 0xba, 0x22, 0xae,
	0x84, 0xba, 0x4b, 0xa3, 0x72, 0x2a, 0x41, 0x98, 0x15, 0x79, 0x1e, 0x3d, 0x86, 0x01, 0x5a, 0xb2,
	0xfa, 0x8a, 0x0c, 0x96, 0x2c, 0x8f, 0xfd, 0x94, 0x4d, 0x22, 0xf1, 0x9c, 0x51, 0x91, 0x24, 0x65,
	0x35, 0x7e, 0x1c, 0xcd, 0x78, 0x32, 0xcd, 0x72, 0x54, 0x50, 0x9d, 0x73, 0xd8, 0x57, 0x63, 0xc3,
	0x94, 0x09, 0x7f, 0x9c, 0x4a, 0x0d, 0x14, 0xc1, 0x22, 0xa6, 0xa1, 0xd6, 0xfe, 0xef, 0x9d, 0xbf,
	0x2d, 0xfc, 0xd9, 0x6b, 0xb0, 0xe2, 0xb3, 0x0b, 0xba, 0x9c, 0x91, 0xf2, 0x74, 0xc6, 0xd6, 0xf9,
	0x96, 0xa5, 0x07, 0xf6, 0x8c, 0xa9, 0x0b, 0x12, 0x95, 0x6f, 0x9d, 0x12, 0x28, 0xab, 0x6b, 0xe0,
	0x66, 0xab, 0x68, 0x97, 0x1b, 0x1f, 0x81, 0x6e, 0x18, 0x58, 0x05, 0x7d, 0x60, 0xf5, 0xac, 0x2f,
	0x57, 0xae, 0x63, 0xa1, 0x44, 0xdb, 0x50, 0x36, 0x51, 0xac, 0x9e, 0xdb, 0x31, 0x49, 0xae, 0x61,
	0x01, 0x79, 0xb7, 0xc3, 0x14, 0x6a, 0xab, 0x3d, 0x35, 0xad, 0x3b, 0xfb, 0x42, 0xbe, 0xb5, 0x0b,
	0xd5, 0x2b, 0xbb, 0x7b, 0x65, 0x39, 0xa6, 0x97, 0x0d, 0xca, 0xa1, 0x1d, 0xa5, 0x41, 0xe7, 0xbc,
	0x67, 0x0d, 0x88, 0xd6, 0xf8, 0x0c, 0x1a, 0xae, 0x34, 0xaa, 0xbf, 0x5e, 0x70, 0x7c, 0x09, 0xd3,
	0x65, 0xe3, 0x43, 0x4e, 0x7a, 0xb4, 0xb4, 0x85, 0x68, 0x72, 0xd4, 0xd0, 0x76, 0xf0, 0x0e, 0xb7,
	0xcb, 0x51, 0xf9, 0x86, 0x0f, 0x7b, 0x9b, 0x56, 0x6b, 0x0f, 0x76, 0x56, 0xf3, 0x1c, 0x6b, 0x30,
	0x74, 0x6f, 0xae, 0xb3, 0xf0, 0x0e, 0xed, 0x4b, 0x19, 0x5e, 0x24, 0xd6, 0x77, 0xcf, 0xed, 0x9e,
	0xe5, 0xb5, 0xbb, 0x38, 0x77, 0x7d, 0xfc, 0xd4, 0x25, 0xf9, 0xdf, 0x8e, 0xa7, 0x5d, 0x52, 0xf8,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x8f, 0x21, 0x1e, 0x02, 0x05, 0x00, 0x00,
}
