// Code generated by protoc-gen-go.
// source: juxiaoresp.proto
// DO NOT EDIT!

/*
Package juxiaoresp is a generated protocol buffer package.

It is generated from these files:
	juxiaoresp.proto

It has these top-level messages:
	BidResponse
*/
package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type BidResponse_Event_Type int32

const (
	BidResponse_SHOW           BidResponse_Event_Type = 1
	BidResponse_CLICK          BidResponse_Event_Type = 2
	BidResponse_OPEN           BidResponse_Event_Type = 3
	BidResponse_BEGIN_DOWNLOAD BidResponse_Event_Type = 4
	BidResponse_DOWNLOAD       BidResponse_Event_Type = 5
	BidResponse_INSTALL        BidResponse_Event_Type = 6
	BidResponse_ACTIVE         BidResponse_Event_Type = 7
)

var BidResponse_Event_Type_name = map[int32]string{
	1: "SHOW",
	2: "CLICK",
	3: "OPEN",
	4: "BEGIN_DOWNLOAD",
	5: "DOWNLOAD",
	6: "INSTALL",
	7: "ACTIVE",
}
var BidResponse_Event_Type_value = map[string]int32{
	"SHOW":           1,
	"CLICK":          2,
	"OPEN":           3,
	"BEGIN_DOWNLOAD": 4,
	"DOWNLOAD":       5,
	"INSTALL":        6,
	"ACTIVE":         7,
}

func (x BidResponse_Event_Type) Enum() *BidResponse_Event_Type {
	p := new(BidResponse_Event_Type)
	*p = x
	return p
}
func (x BidResponse_Event_Type) String() string {
	return proto.EnumName(BidResponse_Event_Type_name, int32(x))
}
func (x *BidResponse_Event_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidResponse_Event_Type_value, data, "BidResponse_Event_Type")
	if err != nil {
		return err
	}
	*x = BidResponse_Event_Type(value)
	return nil
}
func (BidResponse_Event_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 0} }

type BidResponse_Creative_Open_Type int32

const (
	BidResponse_Creative_ALL   BidResponse_Creative_Open_Type = 0
	BidResponse_Creative_INNER BidResponse_Creative_Open_Type = 1
	BidResponse_Creative_OUTER BidResponse_Creative_Open_Type = 2
)

var BidResponse_Creative_Open_Type_name = map[int32]string{
	0: "ALL",
	1: "INNER",
	2: "OUTER",
}
var BidResponse_Creative_Open_Type_value = map[string]int32{
	"ALL":   0,
	"INNER": 1,
	"OUTER": 2,
}

func (x BidResponse_Creative_Open_Type) Enum() *BidResponse_Creative_Open_Type {
	p := new(BidResponse_Creative_Open_Type)
	*p = x
	return p
}
func (x BidResponse_Creative_Open_Type) String() string {
	return proto.EnumName(BidResponse_Creative_Open_Type_name, int32(x))
}
func (x *BidResponse_Creative_Open_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidResponse_Creative_Open_Type_value, data, "BidResponse_Creative_Open_Type")
	if err != nil {
		return err
	}
	*x = BidResponse_Creative_Open_Type(value)
	return nil
}
func (BidResponse_Creative_Open_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 6, 0}
}

type BidResponse_Creative_Interaction_Type int32

const (
	BidResponse_Creative_ANY            BidResponse_Creative_Interaction_Type = 0
	BidResponse_Creative_NO_INTERACTION BidResponse_Creative_Interaction_Type = 1
	BidResponse_Creative_BROWSE         BidResponse_Creative_Interaction_Type = 2
	BidResponse_Creative_DOWNLOAD       BidResponse_Creative_Interaction_Type = 3
	BidResponse_Creative_DIALING        BidResponse_Creative_Interaction_Type = 4
	BidResponse_Creative_MESSAGE        BidResponse_Creative_Interaction_Type = 5
	BidResponse_Creative_MAIL           BidResponse_Creative_Interaction_Type = 6
)

var BidResponse_Creative_Interaction_Type_name = map[int32]string{
	0: "ANY",
	1: "NO_INTERACTION",
	2: "BROWSE",
	3: "DOWNLOAD",
	4: "DIALING",
	5: "MESSAGE",
	6: "MAIL",
}
var BidResponse_Creative_Interaction_Type_value = map[string]int32{
	"ANY":            0,
	"NO_INTERACTION": 1,
	"BROWSE":         2,
	"DOWNLOAD":       3,
	"DIALING":        4,
	"MESSAGE":        5,
	"MAIL":           6,
}

func (x BidResponse_Creative_Interaction_Type) Enum() *BidResponse_Creative_Interaction_Type {
	p := new(BidResponse_Creative_Interaction_Type)
	*p = x
	return p
}
func (x BidResponse_Creative_Interaction_Type) String() string {
	return proto.EnumName(BidResponse_Creative_Interaction_Type_name, int32(x))
}
func (x *BidResponse_Creative_Interaction_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidResponse_Creative_Interaction_Type_value, data, "BidResponse_Creative_Interaction_Type")
	if err != nil {
		return err
	}
	*x = BidResponse_Creative_Interaction_Type(value)
	return nil
}
func (BidResponse_Creative_Interaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 6, 1}
}

type BidResponse_Creative_Adm_Type int32

const (
	BidResponse_Creative_PIC    BidResponse_Creative_Adm_Type = 0
	BidResponse_Creative_HTML   BidResponse_Creative_Adm_Type = 1
	BidResponse_Creative_NATIVE BidResponse_Creative_Adm_Type = 3
)

var BidResponse_Creative_Adm_Type_name = map[int32]string{
	0: "PIC",
	1: "HTML",
	3: "NATIVE",
}
var BidResponse_Creative_Adm_Type_value = map[string]int32{
	"PIC":    0,
	"HTML":   1,
	"NATIVE": 3,
}

func (x BidResponse_Creative_Adm_Type) Enum() *BidResponse_Creative_Adm_Type {
	p := new(BidResponse_Creative_Adm_Type)
	*p = x
	return p
}
func (x BidResponse_Creative_Adm_Type) String() string {
	return proto.EnumName(BidResponse_Creative_Adm_Type_name, int32(x))
}
func (x *BidResponse_Creative_Adm_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidResponse_Creative_Adm_Type_value, data, "BidResponse_Creative_Adm_Type")
	if err != nil {
		return err
	}
	*x = BidResponse_Creative_Adm_Type(value)
	return nil
}
func (BidResponse_Creative_Adm_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 6, 2}
}

type BidResponse struct {
	Bid              *string            `protobuf:"bytes,1,req,name=bid" json:"bid,omitempty"`
	Ads              []*BidResponse_Ads `protobuf:"bytes,2,rep,name=ads" json:"ads,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *BidResponse) Reset()                    { *m = BidResponse{} }
func (m *BidResponse) String() string            { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()               {}
func (*BidResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *BidResponse) GetBid() string {
	if m != nil && m.Bid != nil {
		return *m.Bid
	}
	return ""
}

func (m *BidResponse) GetAds() []*BidResponse_Ads {
	if m != nil {
		return m.Ads
	}
	return nil
}

type BidResponse_InteractionObject struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Deeplink         *string `protobuf:"bytes,2,opt,name=deeplink" json:"deeplink,omitempty"`
	Phone            *string `protobuf:"bytes,3,req,name=phone" json:"phone,omitempty"`
	Mail             *string `protobuf:"bytes,4,req,name=mail" json:"mail,omitempty"`
	Msg              *string `protobuf:"bytes,5,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse_InteractionObject) Reset()         { *m = BidResponse_InteractionObject{} }
func (m *BidResponse_InteractionObject) String() string { return proto.CompactTextString(m) }
func (*BidResponse_InteractionObject) ProtoMessage()    {}
func (*BidResponse_InteractionObject) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 0}
}

func (m *BidResponse_InteractionObject) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *BidResponse_InteractionObject) GetDeeplink() string {
	if m != nil && m.Deeplink != nil {
		return *m.Deeplink
	}
	return ""
}

func (m *BidResponse_InteractionObject) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *BidResponse_InteractionObject) GetMail() string {
	if m != nil && m.Mail != nil {
		return *m.Mail
	}
	return ""
}

func (m *BidResponse_InteractionObject) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type BidResponse_Img struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Width            *int32  `protobuf:"varint,2,req,name=width" json:"width,omitempty"`
	Height           *int32  `protobuf:"varint,3,req,name=height" json:"height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse_Img) Reset()                    { *m = BidResponse_Img{} }
func (m *BidResponse_Img) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_Img) ProtoMessage()               {}
func (*BidResponse_Img) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 1} }

func (m *BidResponse_Img) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *BidResponse_Img) GetWidth() int32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *BidResponse_Img) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type BidResponse_Title struct {
	Text             *string `protobuf:"bytes,1,req,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse_Title) Reset()                    { *m = BidResponse_Title{} }
func (m *BidResponse_Title) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_Title) ProtoMessage()               {}
func (*BidResponse_Title) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 2} }

func (m *BidResponse_Title) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type BidResponse_EventTrack struct {
	EventType        *BidResponse_Event_Type `protobuf:"varint,1,req,name=event_type,enum=BidResponse_Event_Type" json:"event_type,omitempty"`
	NotifyUrl        []string                `protobuf:"bytes,2,rep,name=notify_url" json:"notify_url,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *BidResponse_EventTrack) Reset()                    { *m = BidResponse_EventTrack{} }
func (m *BidResponse_EventTrack) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_EventTrack) ProtoMessage()               {}
func (*BidResponse_EventTrack) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 3} }

func (m *BidResponse_EventTrack) GetEventType() BidResponse_Event_Type {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return BidResponse_SHOW
}

func (m *BidResponse_EventTrack) GetNotifyUrl() []string {
	if m != nil {
		return m.NotifyUrl
	}
	return nil
}

type BidResponse_Native struct {
	Img              *BidResponse_Img   `protobuf:"bytes,1,req,name=img" json:"img,omitempty"`
	Title            *BidResponse_Title `protobuf:"bytes,2,req,name=title" json:"title,omitempty"`
	Logo             *string            `protobuf:"bytes,3,req,name=logo" json:"logo,omitempty"`
	Desc             *string            `protobuf:"bytes,4,req,name=desc" json:"desc,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *BidResponse_Native) Reset()                    { *m = BidResponse_Native{} }
func (m *BidResponse_Native) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_Native) ProtoMessage()               {}
func (*BidResponse_Native) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 4} }

func (m *BidResponse_Native) GetImg() *BidResponse_Img {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *BidResponse_Native) GetTitle() *BidResponse_Title {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *BidResponse_Native) GetLogo() string {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return ""
}

func (m *BidResponse_Native) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

type BidResponse_Adm struct {
	Source           *string             `protobuf:"bytes,1,req,name=source" json:"source,omitempty"`
	Native           *BidResponse_Native `protobuf:"bytes,2,req,name=native" json:"native,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BidResponse_Adm) Reset()                    { *m = BidResponse_Adm{} }
func (m *BidResponse_Adm) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_Adm) ProtoMessage()               {}
func (*BidResponse_Adm) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 5} }

func (m *BidResponse_Adm) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *BidResponse_Adm) GetNative() *BidResponse_Native {
	if m != nil {
		return m.Native
	}
	return nil
}

type BidResponse_Creative struct {
	BannerId          *int32                                 `protobuf:"varint,1,req,name=banner_id" json:"banner_id,omitempty"`
	AdspaceSlotSeq    *int32                                 `protobuf:"varint,2,req,name=adspace_slot_seq" json:"adspace_slot_seq,omitempty"`
	OpenType          *BidResponse_Creative_Open_Type        `protobuf:"varint,3,req,name=open_type,enum=BidResponse_Creative_Open_Type" json:"open_type,omitempty"`
	InteractionType   *BidResponse_Creative_Interaction_Type `protobuf:"varint,4,req,name=interaction_type,enum=BidResponse_Creative_Interaction_Type" json:"interaction_type,omitempty"`
	InteractionObject *BidResponse_InteractionObject         `protobuf:"bytes,5,req,name=interaction_object" json:"interaction_object,omitempty"`
	PackageName       *string                                `protobuf:"bytes,6,req,name=package_name" json:"package_name,omitempty"`
	AdmType           *BidResponse_Creative_Adm_Type         `protobuf:"varint,7,req,name=adm_type,enum=BidResponse_Creative_Adm_Type" json:"adm_type,omitempty"`
	Adm               *BidResponse_Adm                       `protobuf:"bytes,8,req,name=adm" json:"adm,omitempty"`
	EventTrack        []*BidResponse_EventTrack              `protobuf:"bytes,9,rep,name=event_track" json:"event_track,omitempty"`
	XXX_unrecognized  []byte                                 `json:"-"`
}

func (m *BidResponse_Creative) Reset()                    { *m = BidResponse_Creative{} }
func (m *BidResponse_Creative) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_Creative) ProtoMessage()               {}
func (*BidResponse_Creative) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 6} }

func (m *BidResponse_Creative) GetBannerId() int32 {
	if m != nil && m.BannerId != nil {
		return *m.BannerId
	}
	return 0
}

func (m *BidResponse_Creative) GetAdspaceSlotSeq() int32 {
	if m != nil && m.AdspaceSlotSeq != nil {
		return *m.AdspaceSlotSeq
	}
	return 0
}

func (m *BidResponse_Creative) GetOpenType() BidResponse_Creative_Open_Type {
	if m != nil && m.OpenType != nil {
		return *m.OpenType
	}
	return BidResponse_Creative_ALL
}

func (m *BidResponse_Creative) GetInteractionType() BidResponse_Creative_Interaction_Type {
	if m != nil && m.InteractionType != nil {
		return *m.InteractionType
	}
	return BidResponse_Creative_ANY
}

func (m *BidResponse_Creative) GetInteractionObject() *BidResponse_InteractionObject {
	if m != nil {
		return m.InteractionObject
	}
	return nil
}

func (m *BidResponse_Creative) GetPackageName() string {
	if m != nil && m.PackageName != nil {
		return *m.PackageName
	}
	return ""
}

func (m *BidResponse_Creative) GetAdmType() BidResponse_Creative_Adm_Type {
	if m != nil && m.AdmType != nil {
		return *m.AdmType
	}
	return BidResponse_Creative_PIC
}

func (m *BidResponse_Creative) GetAdm() *BidResponse_Adm {
	if m != nil {
		return m.Adm
	}
	return nil
}

func (m *BidResponse_Creative) GetEventTrack() []*BidResponse_EventTrack {
	if m != nil {
		return m.EventTrack
	}
	return nil
}

type BidResponse_Ads struct {
	AdspaceId        *string                 `protobuf:"bytes,1,req,name=adspace_id" json:"adspace_id,omitempty"`
	Creative         []*BidResponse_Creative `protobuf:"bytes,2,rep,name=creative" json:"creative,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *BidResponse_Ads) Reset()                    { *m = BidResponse_Ads{} }
func (m *BidResponse_Ads) String() string            { return proto.CompactTextString(m) }
func (*BidResponse_Ads) ProtoMessage()               {}
func (*BidResponse_Ads) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 7} }

func (m *BidResponse_Ads) GetAdspaceId() string {
	if m != nil && m.AdspaceId != nil {
		return *m.AdspaceId
	}
	return ""
}

func (m *BidResponse_Ads) GetCreative() []*BidResponse_Creative {
	if m != nil {
		return m.Creative
	}
	return nil
}

func init() {
	proto.RegisterType((*BidResponse)(nil), "BidResponse")
	proto.RegisterType((*BidResponse_InteractionObject)(nil), "BidResponse.InteractionObject")
	proto.RegisterType((*BidResponse_Img)(nil), "BidResponse.Img")
	proto.RegisterType((*BidResponse_Title)(nil), "BidResponse.Title")
	proto.RegisterType((*BidResponse_EventTrack)(nil), "BidResponse.EventTrack")
	proto.RegisterType((*BidResponse_Native)(nil), "BidResponse.Native")
	proto.RegisterType((*BidResponse_Adm)(nil), "BidResponse.Adm")
	proto.RegisterType((*BidResponse_Creative)(nil), "BidResponse.Creative")
	proto.RegisterType((*BidResponse_Ads)(nil), "BidResponse.Ads")
	proto.RegisterEnum("BidResponse_Event_Type", BidResponse_Event_Type_name, BidResponse_Event_Type_value)
	proto.RegisterEnum("BidResponse_Creative_Open_Type", BidResponse_Creative_Open_Type_name, BidResponse_Creative_Open_Type_value)
	proto.RegisterEnum("BidResponse_Creative_Interaction_Type", BidResponse_Creative_Interaction_Type_name, BidResponse_Creative_Interaction_Type_value)
	proto.RegisterEnum("BidResponse_Creative_Adm_Type", BidResponse_Creative_Adm_Type_name, BidResponse_Creative_Adm_Type_value)
}

var fileDescriptor4 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x94, 0x5f, 0x6f, 0x9b, 0x48,
	0x14, 0xc5, 0x37, 0xc6, 0xd8, 0x70, 0x9d, 0x8d, 0x26, 0xec, 0x46, 0x8b, 0x90, 0x36, 0x4d, 0x5d,
	0xa9, 0x4d, 0xff, 0xc8, 0x6a, 0xfd, 0x98, 0xa7, 0x62, 0x07, 0x25, 0xa8, 0x18, 0xa2, 0x98, 0x36,
	0xaa, 0x54, 0x09, 0x11, 0x33, 0xb1, 0x49, 0xcc, 0x9f, 0xc2, 0x24, 0x4d, 0xbe, 0x5f, 0xa5, 0x7e,
	0xad, 0xde, 0x19, 0x88, 0x13, 0x1a, 0xbf, 0x31, 0x70, 0xef, 0x99, 0x73, 0x7f, 0x73, 0x06, 0x20,
	0x97, 0xd7, 0xb7, 0x71, 0x98, 0x15, 0xb4, 0xcc, 0x07, 0x79, 0x91, 0xb1, 0xac, 0xff, 0x4b, 0x85,
	0xde, 0x28, 0x8e, 0x4e, 0xf1, 0x4d, 0x96, 0x96, 0x54, 0xeb, 0x81, 0x74, 0x1e, 0x47, 0xfa, 0xc6,
	0x5e, 0x6b, 0x5f, 0xd5, 0xfe, 0x07, 0x29, 0x8c, 0x4a, 0xbd, 0xb5, 0x27, 0xed, 0xf7, 0x86, 0x64,
	0xf0, 0xa8, 0x6e, 0x60, 0x46, 0xa5, 0xf1, 0x0d, 0xb6, 0xed, 0x94, 0xd1, 0x22, 0x9c, 0xb1, 0x38,
	0x4b, 0xbd, 0xf3, 0x4b, 0x3a, 0x63, 0x5c, 0xe0, 0xba, 0x58, 0xd6, 0x02, 0x04, 0x94, 0x88, 0xd2,
	0x7c, 0x19, 0xa7, 0x57, 0xa8, 0xb2, 0x81, 0x6f, 0xfe, 0x06, 0x39, 0x5f, 0x64, 0x29, 0xd5, 0x25,
	0x51, 0xb0, 0x09, 0xed, 0x24, 0x8c, 0x97, 0x7a, 0x5b, 0xac, 0xb0, 0x37, 0x29, 0xe7, 0xba, 0xcc,
	0x17, 0xc6, 0x07, 0x90, 0xec, 0x64, 0xde, 0xd4, 0xc3, 0xee, 0x1f, 0x71, 0xc4, 0x16, 0x28, 0xd6,
	0xda, 0x97, 0xb5, 0x2d, 0xe8, 0x2c, 0x68, 0x3c, 0x5f, 0x30, 0xa1, 0x26, 0x1b, 0x3b, 0x20, 0xfb,
	0x31, 0x5b, 0x52, 0x2e, 0xcb, 0xe8, 0x2d, 0xab, 0xba, 0x8c, 0x09, 0x80, 0x75, 0x43, 0x53, 0xe6,
	0xa3, 0xd3, 0x2b, 0xed, 0x2d, 0x00, 0xe5, 0xab, 0x80, 0xdd, 0xe5, 0x54, 0x54, 0x6c, 0x0d, 0xff,
	0x6b, 0xcc, 0x26, 0x8a, 0x03, 0x1f, 0x3f, 0x6b, 0x1a, 0x40, 0x9a, 0xb1, 0xf8, 0xe2, 0x2e, 0xe0,
	0x26, 0x38, 0x08, 0xd5, 0xb8, 0x80, 0x8e, 0x1b, 0xb2, 0xf8, 0x86, 0x72, 0x3e, 0x71, 0x32, 0x17,
	0x1a, 0x7f, 0xf2, 0xe1, 0xd6, 0x9f, 0x83, 0xcc, 0xb8, 0x1d, 0xe1, 0xb6, 0x37, 0xd4, 0x1a, 0x05,
	0x2b, 0xa3, 0xcb, 0x6c, 0x9e, 0x3d, 0xd0, 0x88, 0x68, 0x39, 0xab, 0x68, 0x18, 0x07, 0x20, 0x99,
	0x51, 0xc2, 0x87, 0x2c, 0xb3, 0xeb, 0x62, 0x46, 0x6b, 0x06, 0x2f, 0xa0, 0x93, 0x8a, 0xed, 0x6b,
	0xd9, 0x7f, 0x1a, 0xb2, 0x95, 0x33, 0xe3, 0x67, 0x1b, 0x94, 0x71, 0x41, 0x2b, 0x9b, 0xdb, 0xa0,
	0x9e, 0x87, 0x69, 0x4a, 0x8b, 0xa0, 0x3e, 0x59, 0x59, 0xd3, 0x81, 0xe0, 0xc9, 0xe6, 0xe1, 0x8c,
	0x06, 0xe5, 0x32, 0x63, 0x41, 0x49, 0xbf, 0xd7, 0x4c, 0x87, 0xa0, 0x66, 0x39, 0x4d, 0x2b, 0x3a,
	0x92, 0xa0, 0xf3, 0xac, 0xb1, 0xc3, 0xbd, 0xec, 0xc0, 0xe3, 0x65, 0x82, 0xd2, 0x47, 0x20, 0xf1,
	0x43, 0x10, 0xaa, 0xd6, 0xb6, 0x68, 0x7d, 0xb9, 0xbe, 0xf5, 0x51, 0x6c, 0x2a, 0x85, 0x03, 0xd0,
	0x1e, 0x2b, 0x64, 0x22, 0x4b, 0x22, 0x08, 0xbd, 0xe1, 0x6e, 0x13, 0xec, 0x93, 0xc4, 0xfd, 0x0b,
	0x9b, 0x38, 0xc8, 0x55, 0x38, 0xa7, 0x41, 0x1a, 0x26, 0x54, 0xef, 0x08, 0x4c, 0xef, 0x41, 0x09,
	0xa3, 0xa4, 0xf2, 0xd2, 0x15, 0x5e, 0x76, 0xd7, 0x7b, 0x41, 0xc6, 0x95, 0x07, 0x91, 0xf6, 0x44,
	0x57, 0xd6, 0x9c, 0x26, 0x3f, 0x87, 0x77, 0xd0, 0xab, 0x73, 0xc3, 0x63, 0xa4, 0xab, 0xe2, 0x52,
	0xac, 0x09, 0x8e, 0x48, 0x59, 0xff, 0x0d, 0xa8, 0x0f, 0x7c, 0xba, 0x78, 0x92, 0x8e, 0x43, 0xfe,
	0xd2, 0x54, 0x90, 0x6d, 0xd7, 0xb5, 0x4e, 0xc9, 0x06, 0x7f, 0xf4, 0x3e, 0xfb, 0xf8, 0xd8, 0xea,
	0x27, 0x40, 0x9e, 0x00, 0xe1, 0x2d, 0xee, 0x57, 0x6c, 0xd1, 0x60, 0xcb, 0xf5, 0x02, 0xdb, 0xc5,
	0x52, 0x73, 0xec, 0xdb, 0x9e, 0x8b, 0xbd, 0x00, 0x9d, 0xd1, 0xa9, 0x77, 0x36, 0xb5, 0x48, 0x0b,
	0x33, 0xa3, 0x1c, 0x7a, 0x67, 0xae, 0xe3, 0x99, 0x87, 0x44, 0xc2, 0xdb, 0xd2, 0x3d, 0xb4, 0x4d,
	0xc7, 0x76, 0x8f, 0x48, 0x9b, 0x2f, 0x26, 0xd6, 0x74, 0x6a, 0x1e, 0x59, 0x44, 0xd6, 0x14, 0x68,
	0x4f, 0x4c, 0xdb, 0x21, 0x9d, 0xfe, 0x6b, 0x50, 0x56, 0x33, 0xe3, 0x36, 0x27, 0xf6, 0x18, 0xb7,
	0xc1, 0xcf, 0xc7, 0xfe, 0xc4, 0xa9, 0xc4, 0x5d, 0xd3, 0xb7, 0xbf, 0x58, 0x44, 0x32, 0x46, 0x3c,
	0x82, 0x25, 0xbf, 0x05, 0xf7, 0x69, 0x59, 0xfd, 0x1b, 0x5e, 0x81, 0x32, 0xab, 0x11, 0xd6, 0x3f,
	0x88, 0x9d, 0xb5, 0x7c, 0xfb, 0x17, 0xf5, 0xed, 0xab, 0x36, 0xc4, 0x7d, 0xa6, 0xc7, 0xde, 0x59,
	0x05, 0x60, 0xec, 0xd8, 0xe3, 0x4f, 0x38, 0x03, 0xbe, 0xf4, 0x4e, 0x2c, 0x17, 0xfd, 0xe3, 0xb4,
	0x23, 0xeb, 0xc8, 0x76, 0x83, 0xd5, 0x4c, 0xed, 0xc6, 0x84, 0x32, 0x1f, 0xca, 0x76, 0xa7, 0x3e,
	0xe7, 0xd9, 0xe1, 0x5e, 0x39, 0x14, 0xf4, 0xda, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x79, 0x3b,
	0xcb, 0x3e, 0xdc, 0x04, 0x00, 0x00,
}
